# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
# Setting a larger heap size can improve build performance.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=false

# Enables unit testing in Android projects.
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=false

# Suppress warning for compileSdk 35 with AGP 8.5.2
android.suppressUnsupportedCompileSdk=35
org.gradle.daemon=false
kotlin.incremental=false
android.dependency.useConstraints=true
android.dependency.excludeLibraryComponentsFromConstraints=true
android.r8.strictFullModeForKeepRules=false
android.disallowKotlinSourceSets=false
org.gradle.configuration-cache=true